name: sample-monorepo

static_sites:
- name: frontend
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: frontend
  routes:
  - /

- name: landing
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: landing
  dockerfile_path: Dockerfile
  routes:
  - /landing

services:
- name: api
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: api
  routes:
  - /api

- name: webhook
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: webhook
  routes:
  - /webhook

- name: worker
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: worker
  dockerfile_path: Dockerfile
  run_command: echo 'starting...' && sleep infinity
