name: sample-monorepo

static_sites:
- name: frontend
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: frontend
  index_document: hello.html
  error_document: error.html
  routes:
  - path: /

- name: landing
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: landing
  dockerfile_path: landing/Dockerfile
  output_dir: /workspace
  error_document: error.html
  # build_command: test -f ./ok && cat ./ok
  # run_command: test -f ./ok && cat ./ok
  routes:
  - path: /landing

services:
- name: api
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: api
  routes:
  - path: /api

- name: webhook
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: webhook
  routes:
  - path: /webhook

workers:
- name: worker
  github:
    repo: digitalocean/sample-monorepo
    branch: master
    deploy_on_push: true
  source_dir: worker
  dockerfile_path: worker/Dockerfile
  run_command: sh -c "cat ./ok && sleep infinity"
